---
- name: Ensure Jenkins Home Directory on Docker Host
  file:
    path: "{{ jenkins_home_dir_host }}"
    state: directory
    owner: "{{ jenkins_user_id }}"
    group: "{{ jenkins_group_id }}"

- name: Login to Docker Hub to be able to push the built image
  docker_login:
    username: "{{ docker_hub_username }}"
    password: "{{ docker_hub_password }}"
    reauthorize: yes

- name: Build Jenkins LTS Image from Dockerfile with pre-installed plugins
  docker_image:
    name: "{{ docker_hub_username }}/{{ jenkins_image_name }}"
    build:
      path: "{{ dockerfile_build_path }}"
      args:
        JENKINS_ADMIN: "{{ jenkins_admin_user }}"
        JENKINS_ADMIN_PASS: "{{ jenkins_admin_password }}"
    source: build
    state: present
    tag: "{{ jenkins_image_tag }}"
    push: yes


- name: "Run the Jenkins LTS Container on Port {{ docker_host_port }}"
  docker_container:
    name: "{{ jenkins_instance_name }}"
    image: "{{ docker_hub_username }}/{{ jenkins_image_name }}:{{ jenkins_image_tag }}"
    ports:
      - "{{ docker_host_port }}:8080"
    volumes:
      - "{{ jenkins_home_dir_host }}:{{ jenkins_home_dir_container }}"
    env:
      JAVA_OPTS: "-Djenkins.install.runSetupWizard=false -Dhudson.footerURL={{ jenkins_footer_url }}"
    state: started
    restart: yes
    restart_policy: unless-stopped
    recreate: no
